site_name: Curve Resources
site_url: https://resources.curve.fi/
site_author: CurveFi

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

nav:
  - index.md  
  - Getting Started:
    - base-features/understanding-curve.md  
    - base-features/understanding-crypto-pools.md  
  - $crvUSD:
    - crvusd/understanding-crvusd.md
    - crvusd/markets.md
    - crvusd/loan-creation.md
    - crvusd/loan-details.md
    - crvusd/understanding-tokenomics.md
    - FAQ: crvusd/faq.md
  - $CRV Token:
    - crv-token/understanding-crv.md
    - crv-token/crv-basics.md
    - crv-token/crv-tokenomics.md
    - crv-token/staking-your-crv.md
    - crv-token/claiming-trading-fees.md
  - Liquidity Providers:
    - lp/understanding-curve-pools.md
    - lp/base-and-metapools.md
    - lp/deposit-faqs.md
    - lp/calculating-yield.md
    - Depositing:
      - lp/depositing.md
      - lp/depositing/depositing-into-a-metapool.md
      - lp/depositing/depositing-into-the-susd-pool.md
      - lp/depositing/depositing-into-the-tri-pool.md
      - lp/depositing/depositing-into-the-y-pool.md
  - Reward Gauges:
    - reward-gauges/understanding-gauges.md
    - reward-gauges/creating-a-pool-gauge.md
    - reward-gauges/boosting-your-crv-rewards.md
    - reward-gauges/gauge-weights.md
  - Governance:
    - governance/understanding-governance.md
    - governance/vote-locking-boost.md
    - governance/voting.md
    - governance/snapshot.md
    - Proposals:
      - governance/proposals.md
      - governance/proposals/community-fund.md
      - governance/proposals/creating-a-dao-proposal.md
  - Multichain:
    - multichain/understanding-multichain.md
    - multichain/bridging-funds.md
    - multichain/using-curve-on-fantom.md
    - multichain/using-curve-on-polygon.md
  - Factory Pools:
    - factory-pools/pool-factory.md
    - factory-pools/creating-a-factory-pool.md
    - factory-pools/creating-a-cryptoswap-pool.md
    - factory-pools/understanding-oracles.md
  - Troubleshooting:
    - troubleshooting/support.md
    - troubleshooting/cross-asset-swaps.md
    - troubleshooting/recovering-a-cross-asset-swap.md
    - troubleshooting/dropping-and-replacing-a-stuck-transaction.md
    - troubleshooting/disabling-crypto-wallets-in-brave .md
  - Appendix:
    - faq/glossary.md
    - Security: https://resources.curve.fi/faq/security
  - Links:
    - Curve.fi: https://curve.fi/#/ethereum/swap
    - Curve DAO: https://dao.curve.fi/
    - Github: https://github.com/curvefi/
    - Governance Forum: https://gov.curve.fi/
    - Technical Docs: https://curve.readthedocs.io/toctree.html
    - Twitter: https://twitter.com/curvefinance
    - Techincal Documentation: https://docs.curve.fi/

# extension
markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  # - pymdownx.arithmatex:
      # generic: true

theme:
  name: material
  include_search_page: false
  search_index_only: true
  font:
    text: Roboto
    code: Roboto Mono
  logo: "images/logo.png"
  favicon: "images/logo.png"
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - 'stylesheets/extra.css'

# extra_javascript:
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_name: CurveDocs/curve-resources
repo_url: https://github.com/CurveDocs/curve-resources
