site_name: Curve Resources
site_url: https://resources.curve.fi/
site_author: CurveFi

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

nav:
  - Welcome to Curve Finance: index.md  
  - Getting Started:
    - Understanding Curve v1: base-features/understanding-curve.md  
    - Understanding Curve v2: base-features/understanding-crypto-pools.md  
  - $crvUSD:
    - Understanding crvUSD: crvusd/understanding-crvusd.md
    - Markets: crvusd/markets.md
    - Loan Creation: crvusd/loan-creation.md
    - Loan Details: crvusd/loan-details.md
    - $crvUSD Concepts: crvusd/understanding-tokenomics.md
  - $CRV Token:
    - Understanding $CRV: crv-token/understanding-crv.md
    - $CRV Basics: crv-token/crv-basics.md
    - $CRV Tokenomics: crv-token/crv-tokenomics.md
    - Staking your $CRV: crv-token/staking-your-crv.md
    - Claiming Trading Fees: crv-token/claiming-trading-fees.md

    
# extension
markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

theme:
  name: material
  include_search_page: false
  search_index_only: true
  font:
    text: Roboto
    code: Roboto Mono
  logo: "images/logo.png"
  favicon: "images/logo.png"
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_name: CurveDocs/curve-resources
repo_url: https://github.com/CurveDocs/curve-resources
